In [82]:
from utility import load_cifa100_data,unpickle
from entity import DataArtifact,LabelsArtifact
import numpy as np

In [85]:
train_data_dic = unpickle(r'C:\Users\arunk\Assignments\DL and CV Practical Assignment\Assignment 2\cifar-100-python\train')
meta_data_dic = unpickle(r'C:\Users\arunk\Assignments\DL and CV Practical Assignment\Assignment 2\cifar-100-python\meta')

In [71]:
train_data_dic.keys()

dict_keys(['filenames', 'batch_label', 'fine_labels', 'coarse_labels', 'data'])

In [89]:
train_data = train_data_dic["data"]
train_fine_labels = train_data_dic["fine_labels"]
train_coarse_labels = train_data_dic["coarse_labels"]
train_data

array([[255, 255, 255, ...,  10,  59,  79],
       [255, 253, 253, ..., 253, 253, 255],
       [250, 248, 247, ..., 194, 207, 228],
       ...,
       [248, 240, 236, ..., 180, 174, 205],
       [156, 151, 151, ..., 114, 107, 126],
       [ 31,  30,  31, ...,  72,  69,  67]], dtype=uint8)

In [98]:
train_data_1 = train_data.reshape(len(train_data),3,32,32)
    # 
    # train_fine_labels = np.array(train_fine_labels)
    # train_coarse_labels = np.array(train_coarse_labels)
train_data_1


array([[[[255, 255, 255, ..., 195, 212, 182],
         [255, 254, 254, ..., 170, 161, 146],
         [255, 254, 255, ..., 189, 166, 121],
         ...,
         [148, 142, 140, ...,  30,  65,  76],
         [122, 120, 126, ...,  22,  97, 141],
         [ 87,  88, 101, ...,  34, 105, 138]],

        [[255, 255, 255, ..., 205, 224, 194],
         [255, 254, 254, ..., 176, 168, 154],
         [255, 254, 255, ..., 199, 178, 133],
         ...,
         [185, 182, 179, ...,  17,  62,  77],
         [157, 155, 160, ...,  16, 112, 161],
         [122, 122, 134, ...,  36, 133, 173]],

        [[255, 255, 255, ..., 193, 204, 167],
         [255, 254, 254, ..., 150, 130, 113],
         [255, 254, 255, ..., 169, 130,  87],
         ...,
         [ 79,  57,  60, ...,   1,  15,  20],
         [ 66,  58,  71, ...,   3,  56,  87],
         [ 41,  39,  56, ...,  10,  59,  79]]],


       [[[255, 253, 253, ..., 253, 253, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 

In [101]:
train_data_2 = np.moveaxis(train_data_1,1,3)
train_data_2

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [195, 205, 193],
         [212, 224, 204],
         [182, 194, 167]],

        [[255, 255, 255],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [170, 176, 150],
         [161, 168, 130],
         [146, 154, 113]],

        [[255, 255, 255],
         [254, 254, 254],
         [255, 255, 255],
         ...,
         [189, 199, 169],
         [166, 178, 130],
         [121, 133,  87]],

        ...,

        [[148, 185,  79],
         [142, 182,  57],
         [140, 179,  60],
         ...,
         [ 30,  17,   1],
         [ 65,  62,  15],
         [ 76,  77,  20]],

        [[122, 157,  66],
         [120, 155,  58],
         [126, 160,  71],
         ...,
         [ 22,  16,   3],
         [ 97, 112,  56],
         [141, 161,  87]],

        [[ 87, 122,  41],
         [ 88, 122,  39],
         [101, 134,  56],
         ...,
         [ 34,  36,  10],
        